version: '3.4'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: src/Services/UserService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: src/APIGateways/APIGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - userservice